### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rsouthgate** [microsoft/ApplicationInsights-node.js-native-metrics#10]
I'd like to use this but the pre-build binaries available seem to be for old node versions, the build is pretty ropey in our CI env - needs 4gb of c++ libs on windows agents etc...

The outstanding pull request is needed but hasn't been merged...

So just questioning if this is still maintained?

**Comment by hectorhdzg** [comment]
@rsouthgate this repo is still maintained, thanks for bringing this for our attention, I will take a look at existing PR and merge soon

**Comment by ericdowell** [comment]
@hectorhdzg Could you please build and publish the binary Assets? Last release version had 24 Assets. I'm seeing the following while running `npm i` in a node alpine container:
```
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v64-linux-x64-musl.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for applicationinsights-native-metrics@0.0.6 and node@10.15.3 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.6/native_metrics-v0.0.6-node-v64-linux-x64-musl.tar.gz 
```
I'm required to add the following to my Dockerfile because of the binary assets not being published with the last released version:
```
RUN apk add git python make g++
```

**Comment by hectorhdzg** [comment]
New version including assets must be available now, let us know if you have any issue
