### ISSUE TITLE
Can't resolve '../build/Release/native_metrics' in /out

### ISSUE THREAD

**Issue by dfenske** [microsoft/ApplicationInsights-node.js-native-metrics#4]
I've been using this package for a week or so now, and it's been building fine until just now - both locally and in our build process, I am getting this error when trying to build my project. Can you help?

```
Failed to compile.

./node_modules/applicationinsights-native-metrics/out/main.js
Module not found: Can't resolve '../build/Release/native_metri
cs' in '/Users/***/git/research-center-web/node_modules
/applicationinsights-native-metrics/out'

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (/Users/***/git/research-center-web/node_modules/next/dist/build/index.js:192:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
error Command failed with exit code 1.
```

**Comment by markwolff** [comment]
Sorry for the delay, are you using `0.0.5`? It could be due to it not successfully compiling locally on your system. The folder structure of it in your node_modules should look like this
![image](https://user-images.githubusercontent.com/5515583/67791232-556d9880-fa34-11e9-910f-d5a091e3e76c.png)

**Comment by daniv-msft** [comment]
I'm getting a similar error, even though in my case I only need this package indirectly as a dependency of `vscode-extension-telemetry`.

Here is the error I get:
```
ERROR in ./node_modules/applicationinsights-native-metrics/out/main.js
Module not found: Error: Can't resolve '../build/Release/native_metrics' in 'C:\Users\...\node_modules\applicationinsights-native-metrics\out'
```

I checked and the `native_metrics.node` file does exist locally at the expected path.

This error is related to the use of webpack: `applicationinsights-native-metrics` tries to load `native_metrics.node` through `require("../build/Release/native_metrics")`, but it seems that webpack is unable to load .node files by default.

It is possible to configure webpack to load .node files, using `node-loader` package for example, but:
- `node-loader` doesn't seem to be supported anymore. Alternatives exist (`awesome-node-loader`), but I didn't try them.
- Given that `applicationinsights-native-metrics` uses `require("../build/Release/native_metrics")` without specifying the `.node` extension, it would mean creating a webpack loader rule specifically for this dependency, which isn't great.

@markwolff > Could you please consider adding the `.node` extension explicitely, i.e. `require("../build/Release/native_metrics.node")`?
That way, it would be possible to:
- Add a dependency on node-loader: `npm i --save-dev node-loader`
- Add a loader rule in `webpack.config.js` file:
```
rules: [
    {
        test: /\.node$/,
        loader: 'node-loader'
    }
]
``` 

If anyone has a better alternative, I'm also interested in it. :)

**Comment by LuizFellype** [comment]
@daniv-msft  I tried your suggestion then I got this:
`node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node:1
ELF>05@Г@8@���� ���� �� �  �� � �����$$P�tdD�D�D�<<Q�tdR�td���� �� GNU��N�.��+b8�׫��%B	�P @�@(�
^
ParseError: Unexpected character ''`
