### ISSUE TITLE
can't install applicationinsights-native-metrics

### ISSUE THREAD

**Issue by htorjmen** [microsoft/ApplicationInsights-node.js-native-metrics#9]
Hello, 

Is there anyone knows why i get error when installing applicationinsights-native-metrics.
I have installed already the latest version of applicationinsights but in order to work i need the applicationinsights-native-metrics dependency but i get this error:

`node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.5/native_metrics-v0.0.5-node-v72-win32-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for applicationinsights-native-metrics@0.0.5 and node@12.18.4 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47) 
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)`

**Comment by htorjmen** [comment]
it apears that the version 0.0.5 isn't avalaible and can't download it so i had to download version 0.0.4

**Comment by hectorhdzg** [comment]
@htorjmen  is this still an issue for you? 0.0.5 must be available it was released 2 years ago
https://www.npmjs.com/package/applicationinsights-native-metrics

I'm not familiar with node-pre-gyp but looks like is deprecated now, maybe upgrading will take care of the issue

**Comment by hectorhdzg** [comment]
I can see we are using node-pre-gyp in the package, will look into upgrading in our side, sorry about confusion, let us know if you are still having this issue

**Comment by hectorhdzg** [comment]
Windows binaries must be available for version 0.0.6, let us know if you still have this problem
